package Constructor;

class Case_01{
	// 	this is automatically generated by compiler and if modifier of the constructor is same as class name and 
	//	first line of the code inside constructor is super()
	//	Case_01(){
	//		super();
	//	}
}

class Case_02{
	// this is automatically generated by compiler and if modifier of the constructor is same as class name
	//		Case_01(){
	//			super();
	//		}
}


	public class PrototypeOfDefaultConstructor {
		
		// if programmer not write this code compiler will be generate automatically
		
		public PrototypeOfDefaultConstructor() {
			// First line of the code inside constructor generate super()
			super();
		}

		public static void main(String[] args) {
			// TODO Auto-generated method stub

		}

	}

